extends: airbnb-base
installedESLint: true
env:
  browser: true
  node: true
  mocha: true
plugins:
  - import
rules:
  no-console:
    off
  no-nested-ternary:
    off
  no-trailing-spaces:
    off
  comma-spacing:
    off
  quotes:
    off
  prefer-const:
    off
  no-shadow:
    off
  max-len:
    - error
    - 120
  no-param-reassign:
    off
